[package]
name = "common"
version = "0.1.0"
authors = ["{{authors}}"]
license = "MIT"
edition = "2021"

[dependencies]
serde = { version = "1.0.188", features = ["derive"] }

num-traits = "0.2.16"
num-bigint = { version = "0.4.4", features = ["serde"] }
